### ISSUE TITLE
BitBucket example Maven project

### ISSUE THREAD

**Issue by timpeeters** [autobump/autobump#11]
Create an example Maven project on BitBucket Cloud that can be used to test our bot. The project should contain several third party dependencies, some of which are out-of-date on purpose to test the functionality of our bot. Goal of this issue is not to create a project that contains every possible situation but simply a baseline to get started. The example project can be extended in the future to be able to test the scope of a specific ticket.

Acceptance criteria:
- An example Maven project on BitBucket Cloud with;
- An outdated Maven plugin
- An outdated Maven dependency
- An outdated Maven parent pom (e.g. spring-boot-starter-parent)
- An outdated Maven dependency defined using properties ${checkstyle.version}

**Comment by GrietVermeesch** [comment]
Example created as public repository at: https://grietvermeesch@bitbucket.org/grietvermeesch/testmavenproject.git

**Comment by timpeeters** [comment]
Thanks, some small remarks:

- It is best not to check-in IDE specific configuration files. It is best to remove the .idea folder and 
*.iml file in the root of the project.
- It is best not to check-in the target folder of Maven containing compiled classes. The repository should only contain sources, not the result of a build.
- Afterwards, you can add a .gitignore file in the root of the project to prevent these files from being added to Git:

.gitignore
```
*.iml
.idea
target
```

**Comment by timpeeters** [comment]
Some small problems left while building the example on my machine.
After fixing these, the ticket can go to "done".

1. The correct Spring Boot parent pom uses artifactId `spring-boot-starter-parent` instead of `spring-boot-starter`:

```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.1.0.RELEASE</version>
    </parent>
```

2. The Lombok dependency is so outdated, it gives a problem on my machine when trying to compile with Java 11. We might opt for a less outdated version here. E.g. 1.18.10.

```
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.10</version>
        </dependency>
```
