### ISSUE TITLE
Setup GitHub Pages

### ISSUE THREAD

**Issue by timpeeters** [autobump/autobump#15]
Every great library deserves documentation on how to use it. We'll use GitHub Pages to host a mini site to provide users with the necessary information how to setup and use our bot.

Maybe this is the ideal place to put a button, "Install Autobump", redirecting the user to BitBucket Cloud to complete the oauth flow?

Acceptance criteria:
- Documentation of Autobump can be consulted via GitHub Pages.

References:
- https://pages.github.com/

**Comment by the-jos** [comment]
Github pages is available at https://autobump.github.io/autobump/
