### ISSUE TITLE
MavenDependencyResolver support dependencies and plugins in profiles

### ISSUE THREAD

**Issue by timpeeters** [autobump/autobump#23]
Maven can define `profiles` that can be enabled/disabled on-demand. These `profiles` can also contain `plugins`, `pluginDefinitions`, `dependencies` and `dependencyManagement`.

Add support to Autobump to discover these as well.

[](http://maven.apache.org/guides/introduction/introduction-to-profiles.html)

Acceptance criteria:
- Autobump detected plugins and dependencies inside profiles.
- Automated tests prove that plugins and dependencies inside profiles are detected.

**Comment by the-jos** [comment]
http://maven.apache.org/guides/introduction/introduction-to-profiles.html
