### ISSUE TITLE
Automatic rebase

### ISSUE THREAD

**Issue by timpeeters** [autobump/autobump#59]
User Story:
As a developer,
I want Autobump to automatically rebase pull requests when new commits are made onto the target branch.

E.g. when Autobump created a pull request in the past to bump junit from 4.11 to 4.12 and a developer in the meantime pushes a new commit to master, Autobump should detect that the pull request is possibly outdated and rebase the PR.

**Comment by the-jos** [comment]
Opened new issue for Sprint 4: https://github.com/autobump/autobump/issues/122
